In [1]:
import numpy as np

## DataTypes & Attributes

In [3]:
# Numpy's main datatype is ndarray
a1 = np.array([1, 2 ,3])
a1 

array([1, 2, 3])

In [5]:
a2 = np.array([[1, 2.0, 3.3],
              [4, 5, 6.5]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a2.shape

(2, 3)

In [7]:
# create a DataFrame from Numpy array
import pandas as pd 
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2.Creating Numpy Arrays

In [8]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [9]:
sample_array.dtype

dtype('int64')

In [11]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
range_array = np.arange(0, 10, 3)
range_array

array([0, 3, 6, 9])